# Generated by Django 5.0.3 on 2024-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preview_image", models.ImageField(upload_to="data")),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("data_file", models.FileField(upload_to="data-file")),
            ],
        ),
    ]
