# Generated by Django 4.0 on 2024-04-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('service_rating', models.PositiveIntegerField()),
                ('would_recommend', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('maybe', 'maybe')], max_length=50)),
                ('additional_feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='preview_image',
            field=models.ImageField(upload_to='data_images'),
        ),
    ]
